package Steps;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class CourseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void course() {
    driver.get("https://algoritmika.org/ru");
    driver.manage().window().setSize(new Dimension(1366, 728));
    driver.findElement(By.linkText("Войти")).click();
    js.executeScript("window.scrollTo(7,7)");
    driver.findElement(By.cssSelector(".styles__Wrapper--15cxv60:nth-child(5) span:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".Lesson__Wrapper--ko9dzg:nth-child(9) .styles__LinkedCard--18ngraz:nth-child(3) > .styles__Circle--1fyhc9w")).click();
    driver.findElement(By.cssSelector(".styles__MovingPanel--y4taqu")).click();
    driver.findElement(By.cssSelector(".Controls__Input--1nj87xn")).click();
  }
}
